# Stage 1: Build
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve
FROM node:16-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/build ./build

RUN npm install -g serve

CMD ["serve", "-s", "build"]
EXPOSE 5000
