name: Deploy React Apps to S3

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [testingreact, testsecond]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ./${{ matrix.app }}
          npm install

      - name: Build the application
        run: |
          cd ./${{ matrix.app }}
          npm run build

      - name: List files in build directory
        run: |
          cd ./${{ matrix.app }}
          ls -R build

      - name: Sync built app to S3 for ${{ matrix.app }}
        run: |
          aws s3 sync ./${{ matrix.app }}/build s3://your-s3-bucket-${{ matrix.app }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
